### ISSUE TITLE
Bookmarklet on the web archive page looks like one of our buttons which may be confusing to users

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-web-archive#10]
http://www.nationalarchives.gov.uk/webarchive/information/

**Comment by grange85** [comment]
Checked with @punalsc on the status of this issue 2018-05-21

**Comment by punalsc** [comment]
![screen shot 2018-05-21 at 16 00 39](https://user-images.githubusercontent.com/2183042/40315393-27346814-5d13-11e8-828f-a6bee72c05c7.png)

Does this provide details for the user, to establish if this is a draggable item?

If the user tries to click the button, they will be greeted by an alert
![screen shot 2018-05-21 at 16 28 08](https://user-images.githubusercontent.com/2183042/40315698-05267752-5d14-11e8-9007-acf06f115304.png)
